### ISSUE TITLE
Specifying relative paths to the values within the parameters?

### ISSUE THREAD

**Issue by narun4sk** [salt-formulas/reclass#90]
Given the following:
```
parameters:
  elasticsearch:
    image: "quay.io/pires/docker-elasticsearch-kubernetes:5.5.0"
    java_opts: "-Xms512m -Xmx512m"
    replicas: 1
    masters: 1
    roles:
      master:
        image: ${elasticsearch:image}
```

Instead of specifying `${elasticsearch:image}` I would like to be able to use a relative path, something similar to `${...:image}`. 

Hence:
- `${.:key_name}` - looks up `key_name` in the local context (here all keys within `master`)
- `${..:key_name}` - looks up `key_name` in the context one level up (here all keys within `roles`)
- etc...
